name: verify

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  verify:
    name: verify
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.2

      - name: lint
        run: terraform fmt -check
